### PR TITLE
allows compatibility with ruby 2.2+ and Rails 4.2+

### PR DESCRIPTION
**Pull request by danielnc**

### CODE REVIEW

**Comment by danielnc** [comment]
@spectator I suggest dropping support for older rails versions and ruby versions

Happy to work on that

**Comment by spectator** [comment]
@danielnc I'm totally fine with removing old rails/ruby versions support if you want to work on that

**Comment by danielnc** [comment]
@spectator Done!

**Comment by spectator** [comment]
Great work @danielnc ! thank you

**Comment by spectator** [comment]
New gem version is out.

**Pull request merged**
